package cn.com.infcn.core.pageModelAdd;
// Generated 2016-5-25 16:13:02 by Hibernate Tools 4.0.0.Final

import java.util.ArrayList;
import java.util.List;

/**
 * TgenButton generated by hbm2java
 */
public class GenButton implements java.io.Serializable {

	private String id;
	private String name;
	private List<GenPage> genPages = new ArrayList<GenPage>();
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public List<GenPage> getGenPages() {
		return genPages;
	}
	public void setGenPages(List<GenPage> genPages) {
		this.genPages = genPages;
	}

}
