package cn.com.infcn.core.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

import javax.persistence.FetchType;

import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import java.util.Date;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;



/**
 * 
 * Tbug generated by 项目开发部
 */
@Entity
@Table(name = "ade_bug")
public class Tbug implements java.io.Serializable {

  private static final long serialVersionUID = 1L;

  //
  private String id;
  //
  private Date createdatetime;
  //
  private Date modifydatetime;
  //
  private String name;
  //
  private String note;
  //
  private Tbugtype tbugtype;

  public Tbug() {
  }

  public Tbug(String id) {
    this.id = id;
  }

  public Tbug(String id, Date createdatetime, Date modifydatetime, String name, String note, Tbugtype tbugtype) {
    super();
    this.id = id;
    this.createdatetime = createdatetime;
    this.modifydatetime = modifydatetime;
    this.name = name;
    this.note = note;
    this.tbugtype = tbugtype;
  }

  @Id
  @Column(name = "id", unique = true, nullable = false, length = 32)
  public String getId() {
    return this.id;
  }

  public void setId(String id) {
    this.id = id;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "createdatetime", nullable = true)
  public Date getCreatedatetime() {
    return this.createdatetime;
  }

  public void setCreatedatetime(Date createdatetime) {
    this.createdatetime = createdatetime;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "modifydatetime", nullable = true)
  public Date getModifydatetime() {
    return this.modifydatetime;
  }

  public void setModifydatetime(Date modifydatetime) {
    this.modifydatetime = modifydatetime;
  }

  @Column(name = "name", nullable = true, length = 100)
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  @Column(name = "note", nullable = true)
  public String getNote() {
    return this.note;
  }

  public void setNote(String note) {
    this.note = note;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "bugtype_id")
  public Tbugtype getTbugtype() {
    return this.tbugtype;
  }

  public void setTbugtype(Tbugtype tbugtype) {
    this.tbugtype = tbugtype;
  }
}
