package cn.com.infcn.core.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

import javax.persistence.FetchType;

import javax.persistence.Table;

import javax.persistence.OneToMany;
import java.util.HashSet;
import java.util.Set;


/**
 * 
 * Tbugtype generated by 项目开发部
 */
@Entity
@Table(name = "ade_bugtype")
public class Tbugtype implements java.io.Serializable {

  private static final long serialVersionUID = 1L;

  //
  private String id;
  //
  private String name;
  //
  private Set<Tbug> tbugs =new HashSet<Tbug>(0);

  public Tbugtype() {
  }

  public Tbugtype(String id) {
    this.id = id;
  }

  public Tbugtype(String id, String name, Set<Tbug> tbugs) {
    super();
    this.id = id;
    this.name = name;
    this.tbugs = tbugs;
  }

  @Id
  @Column(name = "id", unique = true, nullable = false, length = 32)
  public String getId() {
    return this.id;
  }

  public void setId(String id) {
    this.id = id;
  }

  @Column(name = "name", nullable = true, length = 100)
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "tbugtype")
  public  Set<Tbug> getTbugs() {
    return this.tbugs;
  }

  public void setTbugs(Set<Tbug> tbugs) { 
    this.tbugs = tbugs; 
  }
}
