package cn.com.infcn.core.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

import javax.persistence.FetchType;

import javax.persistence.Table;

import javax.persistence.OneToMany;
import java.util.HashSet;
import java.util.Set;


/**
 * 
 * TdictionaryType generated by 项目开发部
 */
@Entity
@Table(name = "ade_dictionary_type")
public class TdictionaryType implements java.io.Serializable {

  private static final long serialVersionUID = 1L;

  //
  private String id;
  //
  private String zdTypeCode;
  //
  private String zdTypeDesc;
  //
  private String zdTypeName;
  //
  private Integer zdTypeSort;
  //
  private String zdTypeUse;
  //
  private Set<Tdictionary> tdictionaries =new HashSet<Tdictionary>(0);

  public TdictionaryType() {
  }

  public TdictionaryType(String id) {
    this.id = id;
  }

  public TdictionaryType(String id, String zdTypeCode, String zdTypeDesc, String zdTypeName, Integer zdTypeSort, String zdTypeUse, Set<Tdictionary> tdictionaries) {
    super();
    this.id = id;
    this.zdTypeCode = zdTypeCode;
    this.zdTypeDesc = zdTypeDesc;
    this.zdTypeName = zdTypeName;
    this.zdTypeSort = zdTypeSort;
    this.zdTypeUse = zdTypeUse;
    this.tdictionaries = tdictionaries;
  }

  @Id
  @Column(name = "ID", unique = true, nullable = false, length = 32)
  public String getId() {
    return this.id;
  }

  public void setId(String id) {
    this.id = id;
  }

  @Column(name = "ZD_TYPE_CODE", nullable = false, length = 32)
  public String getZdTypeCode() {
    return this.zdTypeCode;
  }

  public void setZdTypeCode(String zdTypeCode) {
    this.zdTypeCode = zdTypeCode;
  }

  @Column(name = "ZD_TYPE_DESC", nullable = false, length = 255)
  public String getZdTypeDesc() {
    return this.zdTypeDesc;
  }

  public void setZdTypeDesc(String zdTypeDesc) {
    this.zdTypeDesc = zdTypeDesc;
  }

  @Column(name = "ZD_TYPE_NAME", nullable = false, length = 100)
  public String getZdTypeName() {
    return this.zdTypeName;
  }

  public void setZdTypeName(String zdTypeName) {
    this.zdTypeName = zdTypeName;
  }

  @Column(name = "ZD_TYPE_SORT", nullable = true, length = 11)
  public Integer getZdTypeSort() {
    return this.zdTypeSort;
  }

  public void setZdTypeSort(Integer zdTypeSort) {
    this.zdTypeSort = zdTypeSort;
  }

  @Column(name = "ZD_TYPE_USE", nullable = false, length = 2)
  public String getZdTypeUse() {
    return this.zdTypeUse;
  }

  public void setZdTypeUse(String zdTypeUse) {
    this.zdTypeUse = zdTypeUse;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "tdictionaryType")
  public  Set<Tdictionary> getTdictionaries() {
    return this.tdictionaries;
  }

  public void setTdictionaries(Set<Tdictionary> tdictionaries) { 
    this.tdictionaries = tdictionaries; 
  }
}
