package cn.com.infcn.core.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

import javax.persistence.FetchType;

import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;



/**
 * 
 * Tdictionary generated by 项目开发部
 */
@Entity
@Table(name = "ade_dictionary")
public class Tdictionary implements java.io.Serializable {

  private static final long serialVersionUID = 1L;

  //
  private String id;
  //
  private String zdCode;
  //
  private String zdDesc;
  //
  private String zdName;
  //
  private Integer zdSort;
  //
  private String zdUse;
  //
  private TdictionaryType tdictionaryType;

  public Tdictionary() {
  }

  public Tdictionary(String id) {
    this.id = id;
  }

  public Tdictionary(String id, String zdCode, String zdDesc, String zdName, Integer zdSort, String zdUse, TdictionaryType tdictionaryType) {
    super();
    this.id = id;
    this.zdCode = zdCode;
    this.zdDesc = zdDesc;
    this.zdName = zdName;
    this.zdSort = zdSort;
    this.zdUse = zdUse;
    this.tdictionaryType = tdictionaryType;
  }

  @Id
  @Column(name = "ID", unique = true, nullable = false, length = 32)
  public String getId() {
    return this.id;
  }

  public void setId(String id) {
    this.id = id;
  }

  @Column(name = "ZD_CODE", nullable = false, length = 60)
  public String getZdCode() {
    return this.zdCode;
  }

  public void setZdCode(String zdCode) {
    this.zdCode = zdCode;
  }

  @Column(name = "ZD_DESC", nullable = true, length = 255)
  public String getZdDesc() {
    return this.zdDesc;
  }

  public void setZdDesc(String zdDesc) {
    this.zdDesc = zdDesc;
  }

  @Column(name = "ZD_NAME", nullable = false, length = 100)
  public String getZdName() {
    return this.zdName;
  }

  public void setZdName(String zdName) {
    this.zdName = zdName;
  }

  @Column(name = "ZD_SORT", nullable = true, length = 11)
  public Integer getZdSort() {
    return this.zdSort;
  }

  public void setZdSort(Integer zdSort) {
    this.zdSort = zdSort;
  }

  @Column(name = "ZD_USE", nullable = false, length = 2)
  public String getZdUse() {
    return this.zdUse;
  }

  public void setZdUse(String zdUse) {
    this.zdUse = zdUse;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "ZD_TYPE_ID")
  public TdictionaryType getTdictionaryType() {
    return this.tdictionaryType;
  }

  public void setTdictionaryType(TdictionaryType tdictionaryType) {
    this.tdictionaryType = tdictionaryType;
  }
}
