package cn.com.infcn.core.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

import javax.persistence.FetchType;

import javax.persistence.Table;

import javax.persistence.OneToMany;
import java.util.HashSet;
import java.util.Set;


/**
 * 
 * TmoduleType generated by 项目开发部
 */
@Entity
@Table(name = "ade_module_type")
public class TmoduleType implements java.io.Serializable {

  private static final long serialVersionUID = 1L;

  //
  private String id;
  //
  private String name;
  //
  private Set<Tmodule> tmodules =new HashSet<Tmodule>(0);

  public TmoduleType() {
  }

  public TmoduleType(String id) {
    this.id = id;
  }

  public TmoduleType(String id, String name, Set<Tmodule> tmodules) {
    super();
    this.id = id;
    this.name = name;
    this.tmodules = tmodules;
  }

  @Id
  @Column(name = "ID", unique = true, nullable = false, length = 32)
  public String getId() {
    return this.id;
  }

  public void setId(String id) {
    this.id = id;
  }

  @Column(name = "NAME", nullable = false, length = 100)
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "tmoduleType")
  public  Set<Tmodule> getTmodules() {
    return this.tmodules;
  }

  public void setTmodules(Set<Tmodule> tmodules) { 
    this.tmodules = tmodules; 
  }
}
