package cn.com.infcn.core.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

import javax.persistence.FetchType;

import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import javax.persistence.OneToMany;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.ManyToMany;
import javax.persistence.JoinTable;

/**
 * 
 * Trole generated by 项目开发部
 */
@Entity
@Table(name = "ade_role")
public class Trole implements java.io.Serializable {

  private static final long serialVersionUID = 1L;

  //
  private String id;
  //
  private String roleDesc;
  //
  private String roleName;
  //
  private Integer roleSort;
  //
  private Trole trole;
  /** 是否为内置角色，1位内置角色，其它为非内置角色 */
  private Integer roleIsBuildin;
  //
  private Set<Trole> troles =new HashSet<Trole>(0);
  
  private Set<Tmodule> tmodules =new HashSet<Tmodule>(0);
  
  private Set<Tuser> tusers =new HashSet<Tuser>(0);

  public Trole() {
  }

  public Trole(String id) {
    this.id = id;
  }

  public Trole(String id, String roleDesc, String roleName, Integer roleSort, Trole trole, Integer roleIsBuildin, Set<Trole> troles, Set<Tmodule> tmodules, Set<Tuser> tusers) {
    super();
    this.id = id;
    this.roleDesc = roleDesc;
    this.roleName = roleName;
    this.roleSort = roleSort;
    this.trole = trole;
    this.roleIsBuildin = roleIsBuildin;
    this.troles = troles;
    this.tmodules = tmodules;
    this.tusers = tusers;
  }

  @Id
  @Column(name = "ID", unique = true, nullable = false, length = 32)
  public String getId() {
    return this.id;
  }

  public void setId(String id) {
    this.id = id;
  }

  @Column(name = "ROLE_DESC", nullable = true, length = 255)
  public String getRoleDesc() {
    return this.roleDesc;
  }

  public void setRoleDesc(String roleDesc) {
    this.roleDesc = roleDesc;
  }

  @Column(name = "ROLE_NAME", nullable = false, length = 100)
  public String getRoleName() {
    return this.roleName;
  }

  public void setRoleName(String roleName) {
    this.roleName = roleName;
  }

  @Column(name = "ROLE_SORT", nullable = true, length = 11)
  public Integer getRoleSort() {
    return this.roleSort;
  }

  public void setRoleSort(Integer roleSort) {
    this.roleSort = roleSort;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "ROLE_PID")
  public Trole getTrole() {
    return this.trole;
  }

  public void setTrole(Trole trole) {
    this.trole = trole;
  }

  @Column(name = "ROLE_IS_BUILDIN", nullable = true, length = 1)
  public Integer getRoleIsBuildin() {
    return this.roleIsBuildin;
  }

  public void setRoleIsBuildin(Integer roleIsBuildin) {
    this.roleIsBuildin = roleIsBuildin;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "trole")
  public  Set<Trole> getTroles() {
    return this.troles;
  }

  public void setTroles(Set<Trole> troles) { 
    this.troles = troles; 
  }

  @ManyToMany(fetch = FetchType.LAZY)
  @JoinTable(name = "ade_role_module", joinColumns = { @JoinColumn(name = "ROLE_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "MODULE_ID", nullable = false, updatable = false) })
  public Set<Tmodule> getTmodules() {
    return this.tmodules;
  }

  public void setTmodules(Set<Tmodule> tmodules) {
    this.tmodules = tmodules;
  }

  @ManyToMany(fetch = FetchType.LAZY)
  @JoinTable(name = "ade_user_role", joinColumns = { @JoinColumn(name = "ROLE_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "USER_ID", nullable = false, updatable = false) })
  public Set<Tuser> getTusers() {
    return this.tusers;
  }

  public void setTusers(Set<Tuser> tusers) {
    this.tusers = tusers;
  }
}
