package cn.com.infcn.core.modelAdd;

// Generated 2016-5-6 9:08:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TattachStandard generated by hbm2java
 */
@Entity
@Table(name = "biz_attach_standard")
public class TattachStandard implements java.io.Serializable {

    private String id;
    private Tstandard tstandard;
    private String name;
    private String url;
    private String size;
    private Integer orderNum;
    private String createUser;
    private Date createTime;

    public TattachStandard() {
    }

    public TattachStandard(String id) {
        this.id = id;
    }

    public TattachStandard(String id, Tstandard tstandard, String name, String url, String size, Integer orderNum,
            String createUser, Date createTime) {
        this.id = id;
        this.tstandard = tstandard;
        this.name = name;
        this.url = url;
        this.size = size;
        this.orderNum = orderNum;
        this.createUser = createUser;
        this.createTime = createTime;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false, length = 32)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "standard_id")
    public Tstandard getTstandard() {
        return this.tstandard;
    }

    public void setTstandard(Tstandard tstandard) {
        this.tstandard = tstandard;
    }

    @Column(name = "name", length = 500)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "url", length = 500)
    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Column(name = "size", length = 50)
    public String getSize() {
        return this.size;
    }

    public void setSize(String size) {
        this.size = size;
    }

    @Column(name = "order_num")
    public Integer getOrderNum() {
        return this.orderNum;
    }

    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    @Column(name = "create_user", length = 32)
    public String getCreateUser() {
        return this.createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

}
