package cn.com.infcn.core.modelAdd;

// Generated 2016-5-6 9:08:51 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TdiseasePrivilegeId generated by hbm2java
 */
@Embeddable
public class TdiseasePrivilegeId implements java.io.Serializable {

    private String userId;
    private String privilegeCodeId;
    private String diseaseId;

    public TdiseasePrivilegeId() {
    }

    public TdiseasePrivilegeId(String userId, String privilegeCodeId, String diseaseId) {
        this.userId = userId;
        this.privilegeCodeId = privilegeCodeId;
        this.diseaseId = diseaseId;
    }

    @Column(name = "user_id", nullable = false, length = 32)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "privilege_code_id", nullable = false, length = 32)
    public String getPrivilegeCodeId() {
        return this.privilegeCodeId;
    }

    public void setPrivilegeCodeId(String privilegeCodeId) {
        this.privilegeCodeId = privilegeCodeId;
    }

    @Column(name = "disease_id", nullable = false, length = 32)
    public String getDiseaseId() {
        return this.diseaseId;
    }

    public void setDiseaseId(String diseaseId) {
        this.diseaseId = diseaseId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof TdiseasePrivilegeId))
            return false;
        TdiseasePrivilegeId castOther = (TdiseasePrivilegeId) other;

        return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
                && castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
                && ((this.getPrivilegeCodeId() == castOther.getPrivilegeCodeId()) || (this.getPrivilegeCodeId() != null
                        && castOther.getPrivilegeCodeId() != null && this.getPrivilegeCodeId().equals(
                        castOther.getPrivilegeCodeId())))
                && ((this.getDiseaseId() == castOther.getDiseaseId()) || (this.getDiseaseId() != null
                        && castOther.getDiseaseId() != null && this.getDiseaseId().equals(castOther.getDiseaseId())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
        result = 37 * result + (getPrivilegeCodeId() == null ? 0 : this.getPrivilegeCodeId().hashCode());
        result = 37 * result + (getDiseaseId() == null ? 0 : this.getDiseaseId().hashCode());
        return result;
    }

}
