package cn.com.infcn.core.modelAdd;
// Generated 2016-5-26 8:46:24 by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * TgenRule generated by hbm2java
 */
@Entity
@Table(name = "tgen_rule")
public class TgenRule implements java.io.Serializable {

	private String id;
	private TgenElement tgenElement;
	private TgenInput tgenInput;
	private TgenCheck tgenCheck;
	private Integer ruleLength;
	private String ruleIsmust;
	private String ruleContext;
	private String ruleSource;

	public TgenRule() {
	}

	public TgenRule(TgenElement tgenElement) {
		this.tgenElement = tgenElement;
	}

	public TgenRule(TgenElement tgenElement, TgenInput tgenInput, TgenCheck tgenCheck, Integer ruleLength,
			String ruleIsmust, String ruleContext, String ruleSource) {
		this.tgenElement = tgenElement;
		this.tgenInput = tgenInput;
		this.tgenCheck = tgenCheck;
		this.ruleLength = ruleLength;
		this.ruleIsmust = ruleIsmust;
		this.ruleContext = ruleContext;
		this.ruleSource = ruleSource;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "tgenElement"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public TgenElement getTgenElement() {
		return this.tgenElement;
	}

	public void setTgenElement(TgenElement tgenElement) {
		this.tgenElement = tgenElement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "finput_type_id")
	public TgenInput getTgenInput() {
		return this.tgenInput;
	}

	public void setTgenInput(TgenInput tgenInput) {
		this.tgenInput = tgenInput;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fcheck_id")
	public TgenCheck getTgenCheck() {
		return this.tgenCheck;
	}

	public void setTgenCheck(TgenCheck tgenCheck) {
		this.tgenCheck = tgenCheck;
	}

	@Column(name = "rule_length")
	public Integer getRuleLength() {
		return this.ruleLength;
	}

	public void setRuleLength(Integer ruleLength) {
		this.ruleLength = ruleLength;
	}

	@Column(name = "rule_ismust", length = 2)
	public String getRuleIsmust() {
		return this.ruleIsmust;
	}

	public void setRuleIsmust(String ruleIsmust) {
		this.ruleIsmust = ruleIsmust;
	}

	@Column(name = "rule_context")
	public String getRuleContext() {
		return this.ruleContext;
	}

	public void setRuleContext(String ruleContext) {
		this.ruleContext = ruleContext;
	}

	@Column(name = "rule_source")
	public String getRuleSource() {
		return this.ruleSource;
	}

	public void setRuleSource(String ruleSource) {
		this.ruleSource = ruleSource;
	}

}
