package cn.com.infcn.core.modelAdd;
// Generated 2016-5-26 8:46:24 by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * TgenButton generated by hbm2java
 */
@Entity
@Table(name = "tgen_button", catalog = "bzpt_new")
public class TgenButton implements java.io.Serializable {

	private String id;
	private String name;
	private Set<TgenPage> tgenPages = new HashSet<TgenPage>(0);

	public TgenButton() {
	}

	public TgenButton(String id) {
		this.id = id;
	}

	public TgenButton(String id, String name, Set<TgenPage> tgenPages) {
		this.id = id;
		this.name = name;
		this.tgenPages = tgenPages;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "tgen_page_buttton", catalog = "bzpt_new", joinColumns = {
			@JoinColumn(name = "button_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "page_id", nullable = false, updatable = false) })
	public Set<TgenPage> getTgenPages() {
		return this.tgenPages;
	}

	public void setTgenPages(Set<TgenPage> tgenPages) {
		this.tgenPages = tgenPages;
	}

}
