package cn.com.infcn.core.modelAdd;
// Generated 2016-5-26 8:46:24 by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TgenInput generated by hbm2java
 */
@Entity
@Table(name = "tgen_input")
public class TgenInput implements java.io.Serializable {

	private String id;
	private String name;
	private Integer orderNum;
	private Set<TgenRule> tgenRules = new HashSet<TgenRule>(0);
	private Set<TgenElement> tgenElements = new HashSet<TgenElement>(0);

	public TgenInput() {
	}

	public TgenInput(String id) {
		this.id = id;
	}

	public TgenInput(String id, String name, Integer orderNum, Set<TgenRule> tgenRules, Set<TgenElement> tgenElements) {
		this.id = id;
		this.name = name;
		this.orderNum = orderNum;
		this.tgenRules = tgenRules;
		this.tgenElements = tgenElements;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "order_num")
	public Integer getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tgenInput")
	public Set<TgenRule> getTgenRules() {
		return this.tgenRules;
	}

	public void setTgenRules(Set<TgenRule> tgenRules) {
		this.tgenRules = tgenRules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tgenInput")
	public Set<TgenElement> getTgenElements() {
		return this.tgenElements;
	}

	public void setTgenElements(Set<TgenElement> tgenElements) {
		this.tgenElements = tgenElements;
	}

}
