package cn.com.infcn.core.modelAdd;
// Generated 2016-5-26 8:46:24 by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import cn.com.infcn.core.pageModelAdd.GenRule;

/**
 * TgenElement generated by hbm2java
 */
@Entity
@Table(name = "tgen_element", catalog = "bzpt_new")
public class TgenElement implements java.io.Serializable {

	private String id;
	private TgenInput tgenInput;
	private TgenPage tgenPage;
	private String elementId;
	private String elementName;
	private String elementNameRemark;
	private Integer elementOrderNumber;
	private Integer elementSize;
	private Integer elementWidth;
	private String elementRules;
	private TgenRule tgenRule;

	private String isGenerator;
	
	private String isVisible;
	


	public TgenElement() {
	}

	public TgenElement(String id) {
		this.id = id;
	}

	public TgenElement(String id, TgenInput tgenInput, TgenPage tgenPage, String elementId, String elementName,
			String elementNameRemark, Integer elementOrderNumber, Integer elementSize, Integer elementWidth,
			String elementRules, TgenRule tgenRule,String isGenerator,String isVisible) {
		this.id = id;
		this.tgenInput = tgenInput;
		this.tgenPage = tgenPage;
		this.elementId = elementId;
		this.elementName = elementName;
		this.elementNameRemark = elementNameRemark;
		this.elementOrderNumber = elementOrderNumber;
		this.elementSize = elementSize;
		this.elementWidth = elementWidth;
		this.elementRules = elementRules;
		this.tgenRule = tgenRule;
		this.isGenerator=isGenerator;
		this.isVisible=isVisible;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "element_input_id")
	public TgenInput getTgenInput() {
		return this.tgenInput;
	}

	public void setTgenInput(TgenInput tgenInput) {
		this.tgenInput = tgenInput;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "element_page_id")
	public TgenPage getTgenPage() {
		return this.tgenPage;
	}

	public void setTgenPage(TgenPage tgenPage) {
		this.tgenPage = tgenPage;
	}

	@Column(name = "element_id", length = 32)
	public String getElementId() {
		return this.elementId;
	}

	public void setElementId(String elementId) {
		this.elementId = elementId;
	}

	@Column(name = "element_name")
	public String getElementName() {
		return this.elementName;
	}

	public void setElementName(String elementName) {
		this.elementName = elementName;
	}

	@Column(name = "element_name_remark")
	public String getElementNameRemark() {
		return this.elementNameRemark;
	}

	public void setElementNameRemark(String elementNameRemark) {
		this.elementNameRemark = elementNameRemark;
	}

	@Column(name = "element_order_number")
	public Integer getElementOrderNumber() {
		return this.elementOrderNumber;
	}

	public void setElementOrderNumber(Integer elementOrderNumber) {
		this.elementOrderNumber = elementOrderNumber;
	}

	@Column(name = "element_size")
	public Integer getElementSize() {
		return this.elementSize;
	}

	public void setElementSize(Integer elementSize) {
		this.elementSize = elementSize;
	}

	@Column(name = "element_width")
	public Integer getElementWidth() {
		return this.elementWidth;
	}

	public void setElementWidth(Integer elementWidth) {
		this.elementWidth = elementWidth;
	}

	@Column(name = "element_rules", length = 500)
	public String getElementRules() {
		return this.elementRules;
	}

	public void setElementRules(String elementRules) {
		this.elementRules = elementRules;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "tgenElement")
	public TgenRule getTgenRule() {
		return this.tgenRule;
	}

	public void setTgenRule(TgenRule tgenRule) {
		this.tgenRule = tgenRule;
	}
	
	@Column(name = "is_generator",length=20)
	public String getIsGenerator() {
		return isGenerator;
	}

	public void setIsGenerator(String isGenerator) {
		this.isGenerator = isGenerator;
	}
	
	@Column(name = "is_visible",length=20)
	public String getIsVisible() {
		return isVisible;
	}

	public void setIsVisible(String isVisible) {
		this.isVisible = isVisible;
	}
}
