package cn.com.infcn.core.modelAdd;
// Generated 2016-5-26 8:46:24 by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TgenPageModel generated by hbm2java
 */
@Entity
@Table(name = "tgen_page_model")
public class TgenPageModel implements java.io.Serializable {

	private String id;
	private String pageModelName;
	private String pageModelFullName;
	private Set<TgenPage> tgenPages = new HashSet<TgenPage>(0);
	private Set<TgenPageModelColum> tgenPageModelColums = new HashSet<TgenPageModelColum>(0);

	public TgenPageModel() {
	}

	public TgenPageModel(String id) {
		this.id = id;
	}

	public TgenPageModel(String id, String pageModelName, String pageModelFullName, Set<TgenPage> tgenPages,
			Set<TgenPageModelColum> tgenPageModelColums) {
		this.id = id;
		this.pageModelName = pageModelName;
		this.pageModelFullName = pageModelFullName;
		this.tgenPages = tgenPages;
		this.tgenPageModelColums = tgenPageModelColums;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "pageModelName")
	public String getPageModelName() {
		return this.pageModelName;
	}

	public void setPageModelName(String pageModelName) {
		this.pageModelName = pageModelName;
	}

	@Column(name = "pageModelFullName")
	public String getPageModelFullName() {
		return this.pageModelFullName;
	}

	public void setPageModelFullName(String pageModelFullName) {
		this.pageModelFullName = pageModelFullName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tgenPageModel")
	public Set<TgenPage> getTgenPages() {
		return this.tgenPages;
	}

	public void setTgenPages(Set<TgenPage> tgenPages) {
		this.tgenPages = tgenPages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tgenPageModel")
	public Set<TgenPageModelColum> getTgenPageModelColums() {
		return this.tgenPageModelColums;
	}

	public void setTgenPageModelColums(Set<TgenPageModelColum> tgenPageModelColums) {
		this.tgenPageModelColums = tgenPageModelColums;
	}

}
