package cn.com.infcn.core.modelAdd;

// Generated 2016-5-6 9:54:36 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tstandard generated by hbm2java
 */
@Entity
@Table(name = "biz_standard")
public class Tstandard implements java.io.Serializable {

    private String id;
    private Tdisease tdisease;
    private String orderNum;
    private String type;
    private String cnTitle;
    private String enTitle;
    private String publishOrg;
    private Integer publishDate;
    private String source;
    private String language;
    private String typeStag;
    private String mmDiseaseName;
    private String tcmDiseaseName;
    private String tcmDiseaseDialectical;
    private String mmStandard;
    private String tcmStandard;
    private String effectTarget;
    private String effectStandard;
    private String remark;
    private String status;
    private String isDel;
    private String createUser;
    private Date createTime;
    private String updateUser;
    private Date updateTime;
    private Set<Tsuggest> tsuggests = new HashSet<Tsuggest>(0);
    private Set<TattachStandard> tattachStandards = new HashSet<TattachStandard>(0);

    public Tstandard() {
    }

    public Tstandard(String id) {
        this.id = id;
    }

    public Tstandard(String id, Tdisease tdisease, String orderNum, String type, String cnTitle, String enTitle,
            String publishOrg, Integer publishDate, String source, String language, String typeStag,
            String mmDiseaseName, String tcmDiseaseName, String tcmDiseaseDialectical, String mmStandard,
            String tcmStandard, String effectTarget, String effectStandard, String remark, String status, String isDel,
            String createUser, Date createTime, String updateUser, Date updateTime, Set<Tsuggest> tsuggests,
            Set<TattachStandard> tattachStandards) {
        this.id = id;
        this.tdisease = tdisease;
        this.orderNum = orderNum;
        this.type = type;
        this.cnTitle = cnTitle;
        this.enTitle = enTitle;
        this.publishOrg = publishOrg;
        this.publishDate = publishDate;
        this.source = source;
        this.language = language;
        this.typeStag = typeStag;
        this.mmDiseaseName = mmDiseaseName;
        this.tcmDiseaseName = tcmDiseaseName;
        this.tcmDiseaseDialectical = tcmDiseaseDialectical;
        this.mmStandard = mmStandard;
        this.tcmStandard = tcmStandard;
        this.effectTarget = effectTarget;
        this.effectStandard = effectStandard;
        this.remark = remark;
        this.status = status;
        this.isDel = isDel;
        this.createUser = createUser;
        this.createTime = createTime;
        this.updateUser = updateUser;
        this.updateTime = updateTime;
        this.tsuggests = tsuggests;
        this.tattachStandards = tattachStandards;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false, length = 32)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "disease_id")
    public Tdisease getTdisease() {
        return this.tdisease;
    }

    public void setTdisease(Tdisease tdisease) {
        this.tdisease = tdisease;
    }

    @Column(name = "order_num", length = 50)
    public String getOrderNum() {
        return this.orderNum;
    }

    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    @Column(name = "type", length = 2)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "cn_title", length = 500)
    public String getCnTitle() {
        return this.cnTitle;
    }

    public void setCnTitle(String cnTitle) {
        this.cnTitle = cnTitle;
    }

    @Column(name = "en_title", length = 500)
    public String getEnTitle() {
        return this.enTitle;
    }

    public void setEnTitle(String enTitle) {
        this.enTitle = enTitle;
    }

    @Column(name = "publish_org", length = 500)
    public String getPublishOrg() {
        return this.publishOrg;
    }

    public void setPublishOrg(String publishOrg) {
        this.publishOrg = publishOrg;
    }

    @Column(name = "publish_date")
    public Integer getPublishDate() {
        return this.publishDate;
    }

    public void setPublishDate(Integer publishDate) {
        this.publishDate = publishDate;
    }

    @Column(name = "source", length = 5000)
    public String getSource() {
        return this.source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    @Column(name = "language", length = 50)
    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    @Column(name = "type_stag", length = 65535)
    public String getTypeStag() {
        return this.typeStag;
    }

    public void setTypeStag(String typeStag) {
        this.typeStag = typeStag;
    }

    @Column(name = "mm_disease_name", length = 500)
    public String getMmDiseaseName() {
        return this.mmDiseaseName;
    }

    public void setMmDiseaseName(String mmDiseaseName) {
        this.mmDiseaseName = mmDiseaseName;
    }

    @Column(name = "tcm_disease_name", length = 500)
    public String getTcmDiseaseName() {
        return this.tcmDiseaseName;
    }

    public void setTcmDiseaseName(String tcmDiseaseName) {
        this.tcmDiseaseName = tcmDiseaseName;
    }

    @Column(name = "tcm_disease_dialectical", length = 65535)
    public String getTcmDiseaseDialectical() {
        return this.tcmDiseaseDialectical;
    }

    public void setTcmDiseaseDialectical(String tcmDiseaseDialectical) {
        this.tcmDiseaseDialectical = tcmDiseaseDialectical;
    }

    @Column(name = "mm_standard", length = 65535)
    public String getMmStandard() {
        return this.mmStandard;
    }

    public void setMmStandard(String mmStandard) {
        this.mmStandard = mmStandard;
    }

    @Column(name = "tcm_standard", length = 65535)
    public String getTcmStandard() {
        return this.tcmStandard;
    }

    public void setTcmStandard(String tcmStandard) {
        this.tcmStandard = tcmStandard;
    }

    @Column(name = "effect_target", length = 65535)
    public String getEffectTarget() {
        return this.effectTarget;
    }

    public void setEffectTarget(String effectTarget) {
        this.effectTarget = effectTarget;
    }

    @Column(name = "effect_standard", length = 65535)
    public String getEffectStandard() {
        return this.effectStandard;
    }

    public void setEffectStandard(String effectStandard) {
        this.effectStandard = effectStandard;
    }

    @Column(name = "remark", length = 65535)
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Column(name = "status", length = 2)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "is_del", length = 2)
    public String getIsDel() {
        return this.isDel;
    }

    public void setIsDel(String isDel) {
        this.isDel = isDel;
    }

    @Column(name = "create_user", length = 100)
    public String getCreateUser() {
        return this.createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Column(name = "update_user", length = 100)
    public String getUpdateUser() {
        return this.updateUser;
    }

    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_time", length = 19)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tstandard")
    public Set<Tsuggest> getTsuggests() {
        return this.tsuggests;
    }

    public void setTsuggests(Set<Tsuggest> tsuggests) {
        this.tsuggests = tsuggests;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tstandard")
    public Set<TattachStandard> getTattachStandards() {
        return this.tattachStandards;
    }

    public void setTattachStandards(Set<TattachStandard> tattachStandards) {
        this.tattachStandards = tattachStandards;
    }

}
