package cn.com.infcn.core.modelAdd;

// Generated 2016-5-6 9:08:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tsuggest generated by hbm2java
 */
@Entity
@Table(name = "biz_suggest")
public class Tsuggest implements java.io.Serializable {

    private String id;
    private Tstandard tstandard;
    private String type;
    private String content;
    private String createUser;
    private Date createTime;
    private String isPass;

    public Tsuggest() {
    }

    public Tsuggest(String id, Tstandard tstandard) {
        this.id = id;
        this.tstandard = tstandard;
    }

    public Tsuggest(String id, Tstandard tstandard, String type, String content, String createUser, Date createTime,
            String isPass) {
        this.id = id;
        this.tstandard = tstandard;
        this.type = type;
        this.content = content;
        this.createUser = createUser;
        this.createTime = createTime;
        this.isPass = isPass;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false, length = 32)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "standard_id", nullable = false)
    public Tstandard getTstandard() {
        return this.tstandard;
    }

    public void setTstandard(Tstandard tstandard) {
        this.tstandard = tstandard;
    }

    @Column(name = "type", length = 2)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "content", length = 65535)
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Column(name = "create_user", length = 32)
    public String getCreateUser() {
        return this.createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Column(name = "isPass", length = 2)
    public String getIsPass() {
        return this.isPass;
    }

    public void setIsPass(String isPass) {
        this.isPass = isPass;
    }

}
