package cn.com.infcn.core.modelAdd;

// Generated 2016-5-6 9:08:51 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tsymptom generated by hbm2java
 */
@Entity
@Table(name = "biz_symptom")
public class Tsymptom implements java.io.Serializable {

    private String id;
    private String name;
    private String diseaseName;
    private String symptomName;
    private String literatureName;
    private String journalName;
    private String yearJournalPage;

    public Tsymptom() {
    }

    public Tsymptom(String id) {
        this.id = id;
    }

    public Tsymptom(String id, String name, String diseaseName, String symptomName, String literatureName,
            String journalName, String yearJournalPage) {
        this.id = id;
        this.name = name;
        this.diseaseName = diseaseName;
        this.symptomName = symptomName;
        this.literatureName = literatureName;
        this.journalName = journalName;
        this.yearJournalPage = yearJournalPage;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false, length = 32)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "name", length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "disease_name", length = 100)
    public String getDiseaseName() {
        return this.diseaseName;
    }

    public void setDiseaseName(String diseaseName) {
        this.diseaseName = diseaseName;
    }

    @Column(name = "symptom_name", length = 100)
    public String getSymptomName() {
        return this.symptomName;
    }

    public void setSymptomName(String symptomName) {
        this.symptomName = symptomName;
    }

    @Column(name = "literature_name")
    public String getLiteratureName() {
        return this.literatureName;
    }

    public void setLiteratureName(String literatureName) {
        this.literatureName = literatureName;
    }

    @Column(name = "journal_name", length = 100)
    public String getJournalName() {
        return this.journalName;
    }

    public void setJournalName(String journalName) {
        this.journalName = journalName;
    }

    @Column(name = "year_journal_page", length = 60)
    public String getYearJournalPage() {
        return this.yearJournalPage;
    }

    public void setYearJournalPage(String yearJournalPage) {
        this.yearJournalPage = yearJournalPage;
    }

}
